theme = "ananke"
relativeURLs = true
baseURL = "/"
title = "Roger Souza"
author = "Roger Souza"
copyright = "Copyright © 2022; all rights reserved."
paginate = 5
languageCode = "pt-br"
DefaultContentLanguage = "pt-br"
enableInlineShortcodes = true

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Início"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "about"
    name = "Sobre Mim"
    url = "/sobre-mim/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disabled = true
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
